### ISSUE TITLE
feat(lang): add .astro support

### ISSUE THREAD

**Issue by cristopher-namchee** [Namchee/dependent#53]
## Overview

Astro is a meta JavaScript framework for building snappy UI. It leverages island architecture and zero-JS by default to achieve faster performance by default. It supports other UI library integrations such as React, Vue, and Svelte.

### Reference

- [Astro Documentation](https://astro.build/)
- [Compiler Package](https://github.com/withastro/compiler)

**Comment by Namchee** [comment]
This is a challenge:

1. There are 2 separate paths to be imported `@astrojs/compiler` for parsing and `@astrojs/compiler/utils` for generic walk function
2. `@astrojs/compiler` doesn't actually provide a walker function for the frontmatter, meaning we have to parse it ourselves.
3. If we must parse it by ourselves, we don't even know if the frontmatter is written in TypeScript or not. If it's written in TypeScript, then we need to load the TS compiler manually since it doesn't get loaded in astro flow.

Generally, this issue can be completely fixed if we move on from `acorn` to `typescript` as JS parser. More details later.
